DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = dual-radio-demo

all: $(CONTIKI_PROJECT)

TARGET ?= zoul
BOARD ?= firefly

CONTIKI = ../../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
